package world.generators.chunk;

public enum ChunkType {

    EMPTY,

    FOREST, OPEN_FIELD, HOME, BACKYARD, TRAPDOOR_FIELD,

    DUNGEON_ENTRANCE, DUNGEON_HALLWAY_NS, DUNGEON_HALLWAY_EW,
    DUNGEON_JUNCTION, DUNGEON_SOUTH_ROOM, DUNGEON_NORTH_ROOM,
    DUNGEON_EAST_ROOM, DUNGEON_WEST_ROOM, DUNGEON_BOSS_ROOM

}
