package assets.definitions;

public class Tile {

    public static final int
            AIR = 0, GRASS = 1, WELL = 2, TALL_GRASS = 3, FLOWERS = 4,
            WOOD_HOUSE_LEFT = 5, WOOD_HOUSE_MIDDLE = 6, WOOD_HOUSE_RIGHT = 7,
            TREE = 8, WOOD_WALL_NORTH = 9, WOOD_WALL_DOOR_NORTH = 10, WOOD_FLOOR = 11,
            WOOD_CORNER_NORTHEAST = 12, WOOD_WALL_EAST = 13, WOOD_WALL_WEST = 14, WOOD_CORNER_NORTHWEST = 15,
            WOOD_WALL_SOUTH = 16, WOOD_WALL_WINDOW_SOUTH = 17, STONE_WALL_NORTH = 18, STONE_WALL_DOOR_NORTH = 19,
            STONE_FLOOR = 20, STONE_CORNER_NORTHEAST = 21, STONE_WALL_EAST = 22, STONE_WALL_WEST = 23,
            STONE_CORNER_NORTHWEST = 24, STONE_WALL_SOUTH = 25, STONE_WALL_WINDOW_SOUTH = 26, STONE_ARCHWAY_SOUTH = 27,
            TRAP_DOOR = 28, STONE_LADDER = 29;

}
